// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Sample();
Q_GHS_KEEP_REFERENCE(qml_register_types_Sample)

class SamplePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    SamplePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Sample;
        Q_UNUSED(registration)
    }
};



#include "Sampleplugin_SamplePlugin.moc"
